match_table_filepath: data/result/mega_table.csv
res_filepath: data/result/final_standings.csv
country_to_highlight: Russian Federation

feature_weights:
  gdp_ppp: .5
  homicide_rate: -0.5
  suicide_rate: -0.6
  purchasing_power_numbeo: .6
  property_price_to_income_numbeo: -0.4
  safety_numbeo: .7
  health_care_numbeo: .8
  traffic_commute_time_numbeo: -0.4
  pollution_numbeo: -0.4
  climate_numbeo: .4
  life_expectancy: 1
  happiness: .8

feature_clips:
  gdp_ppp:
    left_quantile_clip: .02
    right_quantile_clip: .98

features_to_use: [gdp_ppp, homicide_rate, suicide_rate, purchasing_power_numbeo,
                  property_price_to_income_numbeo, safety_numbeo, health_care_numbeo,
                  traffic_commute_time_numbeo, pollution_numbeo, climate_numbeo,
                  life_expectancy, happiness]