match_table_filepath: data/result/2023/all_indicators.csv
res_filepath: data/result/final_standings.csv
country_to_highlight: Russian Federation
is_buddie_highlight: True

feature_weights:
  distance_to_30_years: -0.5
  gdp_ppp: .5
  gini: -0.5
  gender_equality_score: .7
  happiness: .8
  homicide_rate: -0.7
  incarceration_rate: -0.6
  life_expectancy: 1
  numbeo_climate_index: .4
  numbeo_health_care_index: .8
  numbeo_pollution_index: -0.4
  numbeo_property_price_to_income_ratio: -0.4
  numbeo_purchasing_power_index: .6
  numbeo_safety_index: .7
  numbeo_traffic_commute_time_index: -0.4
  press_freedom: -0.7
  suicide_rate: -0.7
  unesco_objects: .5

feature_clips:
  gdp_ppp:
    left_quantile_clip: .02
    right_quantile_clip: .98
  gini:
    left_quantile_clip: .01
    right_quantile_clip: .98
  homicide_rate:
    left_quantile_clip: .01
    right_quantile_clip: .98

features_to_use: [
  distance_to_30_years,
  gdp_ppp,
  gini,
  gender_equality_score,
  happiness,
  homicide_rate,
  incarceration_rate,
  life_expectancy,
  numbeo_climate_index,
  numbeo_health_care_index,
  numbeo_purchasing_power_index,
  numbeo_pollution_index,
  numbeo_property_price_to_income_ratio,
  numbeo_safety_index,
  numbeo_traffic_commute_time_index,
  press_freedom,
  suicide_rate,
  unesco_objects
]
