match_table_filepath: data/result/mega_table.csv
res_filepath: data/result/final_standings.csv
country_to_highlight: Russian Federation
is_buddie_highlight: True

feature_weights:
  climate_numbeo: .4
  distance_to_30_years: -0.5
  gdp_ppp: .5
  gini: -0.5
  happiness: .8
  health_care_numbeo: .8
  homicide_rate: -0.7
  incarceration_rate: -0.6
  life_expectancy: 1
  pollution_numbeo: -0.4
  property_price_to_income_numbeo: -0.4
  purchasing_power_numbeo: .6
  safety_numbeo: .7
  suicide_rate: -0.7
  traffic_commute_time_numbeo: -0.4
  unesco_objects: .5

feature_clips:
  gdp_ppp:
    left_quantile_clip: .02
    right_quantile_clip: .98
  gini:
    left_quantile_clip: .01
    right_quantile_clip: .98
  homicide_rate:
    left_quantile_clip: .01
    right_quantile_clip: .98

features_to_use: [gdp_ppp, homicide_rate, suicide_rate, purchasing_power_numbeo,
                  property_price_to_income_numbeo, safety_numbeo, health_care_numbeo,
                  traffic_commute_time_numbeo, pollution_numbeo, climate_numbeo,
                  life_expectancy, happiness, unesco_objects, distance_to_30_years,
                  gini, incarceration_rate]
